2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:35:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:36:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'roi_halfside'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 173, in draw_contours\n    w = h = self.settings.roi_halfside.val*2\n', "AttributeError: 'LQCollection' object has no attribute 'roi_halfside'\n"]
2020-07-26T18:39:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'cnt'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 92, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'cnt'\n"]
